import React, { PureComponent } from 'react';
class TnC extends PureComponent {
  render() {  
    const {params} = this.props;
    const langSelected = typeof params.lang != 'undefined' ? params.lang.toLowerCase() : 'english';
    const filterLangs = ['Nepali', 'Asamiya', 'Urdu', 'Odia', 'Punjabi'];
    const notSupportedLangs = filterLangs.map((it)=>it.toLowerCase());
    let currentLanguage = notSupportedLangs.includes(langSelected) ? 'english' : langSelected;
    return(
        (()=>{
            switch(currentLanguage) {
                case 'english':
                return(<div className="loot-tnc">
                        <header className="heading">NEWSPOINT LOOT CAMPAIGN: TERMS AND CONDITIONS</header>
                        <article>
                            <p>
                                The Newspoint Loot Campaign (“Campaign”) is organised by Times Internet Limited (“TIL”) to award its users (“You,” “Partner,” “Referrer,” “Participant”) for referring Active Users who sign on to be TIL customers. It was also created to reward these new customers for listening to your great advice in referring us, by offering them a reward for signing up at your referral <br /><br />
                                These Terms and Conditions are a binding agreement between You and TIL and will govern your participation in this Contest. By participating in the Contest, you agree to TIL Application Terms and Conditions and TIL Application Privacy Policy. You are not authorized to participate in the Contest, if you do not agree to these Contest Terms and Conditions in their entirety. <br /><br />
                            </p>
                            <ul>
                                <li>Contest Period: Participation in this Contest is valid from ____2018 commencing at 00:01 hours and culminating on ____ 2018 at 23:59 hours (hereinafter referred to as “Contest Period”).</li>
                                <li>Eligibility: To be considered as eligible for this Contest user must have an account of TIL’s Application titled Newspoint (“Application”), be an Indian Citizen and 18 years of age or above (hereinafter referred to as “Participants”).</li>
                                <li>TIL reserves the right to modify these Contest Terms and Conditions at any time, at its sole discretion, and without notice to You. TIL may also, in its sole discretion, change, cancel, suspend, or modify any aspect of the Contest without notice. TIL also reserves the right to disqualify any user or prospective user at any time from participation in the Contest. </li>
                                <li>How the Contest Works:
                                    <ul>
                                        <li>The Participant shares a TIL URL through e.g. email, Facebook, or any other communication means with a person, the referred; The referred then signs up for a TIL account when they arrive at the TIL Application by opening the TIL URL shared by the Participant in a web browser; and only when the referred customer has signed up and launched the Application once every day for consecutive 2 days from the date of sign up. (“Active User”)</li>
                                        <li>Only successful activations made by the Participant will be considered for the purposes of this Contest.</li>
                                    </ul>
                                </li>
                                <li>Winner Selection:
                                    <ul>
                                        <li>__ winners will be selected based on the number of Active Users refereed by them</li>
                                        <li>The Participants shall be ranked basis the number of Active User’s refereed by them and accordingly Participants eligibility will be governed </li>
                                        <li>Making 1 or more Active Users does not guarantee winning the prize.</li>
                                    </ul>
                                </li>
                                <li>Prize/Gratification:
                                    <ul>
                                        <li>The Participants shall be ranked basis the number of Active User’s refereed by them</li>
                                        <li>Prizes shall be _______________</li>
                                    </ul>
                                </li>
                                <li>The participants selected as winners will be notified through email/Push notifications/Inapp/SMS provided the Participants are registered with Organizer. A communication will be sent to only those Participants who have won in the Contest.</li>
                                <li>Organizer shall not bear any expenses incurred with respect to participating and availing of the Prize by the winner(s).</li>
                                <li>Mere participation in the Contest does not entitle the Participants to win the Prize.</li>
                                <li>This Contest shall not be clubbed/used in conjunction/alongside any prevailing Contest/promotion running by the Organizer.</li>
                                <li>Employees of Organizer (including their family members & relatives) and of their group companies, affiliate or associate companies, shall not be eligible for any of the prize/gratification under this Contest. In case it comes to the knowledge of Organizer that any winner is an employee of Organizer or their family member, Organizer reserves the right to forfeit the gratification/Prize. Further, to participate in contest the Participants needs to have registered Organizer account.</li>
                                <li>Organizer reserves the right to disqualify any transaction or discontinue promotion of the Contest at any time</li>
                                <li>Organizer reserves the right to extend, cancel, discontinue, prematurely withdraw, change, alter or modify this Contest or any part thereof including the eligibility criteria and other pertinent T&C at their sole discretion at any time during its validity as may be required including in view of business exigencies and/or changes by a regulatory authority and/or statutory changes and/or any reasons beyond their control and the same shall be binding on the Participants.</li>
                                <li>In cases of fraudulent/suspicious transactions, Organizer solely reserves the disqualify such Participant.</li>
                                <li>The Prize cannot be exchanged for cash</li>
                            
                            </ul><br />
                            <h4>OTHER TERMS & CONDITIONS: -</h4><br /><br />
                            <ul>
                                <li>The participation in the Contest is open only for the Contest Period for the Indian citizens of 18 years and above of age. Employees of Organizer (including their family members & relatives) and of their affiliate or associate companies, shall not be eligible for any of the Prize under this Contest. In case it comes to the knowledge of Organizer that any Winner is an employee of Organizer or their family member or relative, Organizer reserves the right to forfeit the Prize. Further, to participate in Contest the Participants needs to have registered account on Organizer Platform.</li>
                                <li>The Participants who are residents (permanent/temporary) of any state/union territory within the territory of India shall not be entitled to participate in this Contest, wherever such Contest is prohibited by applicable law.</li>
                                <li>By participating in the Contest, Participants consent to the use of the information available on Organizer platform such as name, score etc. to be communicated to Organisers vendor as required for publication in any media, for the purpose of Winner’s announcement. Organizer may, at its discretion, choose not to disclose the identity of the selected Winner(s) to other Participants unless expressly mentioned herein. The Participants also consent to the information being stored in the servers of Organizer or its service providers.</li>
                                <li>Participants acknowledge and agree that all copyright and trademarks and all other intellectual property rights in the  WAP, M- web, Application, Website and all material or content related to the Contest shall remain, at all times, owned by Organizer. All material and content contained is made available for Participant’s personal and non-commercial use only. Any other use of the material/ content on the platform and/ or any information disseminated by SMS or any other means of communication is strictly prohibited.</li>
                                <li>Subject to any applicable laws; (a) All warranties of any kind whatsoever, whether express or implied, are hereby expressly DISCLAIMED including, but not limited to, meeting of the Participant's requirements or aspirations, timeliness, security, the results or reliability of the Contest, delay in sending or receiving the SMS for participating in the Contest, any type of delay by the Participant/Winner, or the delivery, quality, quantity, participants ability, fitness for use or non-infringement in respect of any goods, services, benefits or Prize/gratification/awards acquired or obtained through the Contest or any transactions effected through the Contest; (b) The Participant expressly agree that his/her participation in the Contest is at his/her sole risk and is governed by the T&C herein; and (c) No advice or information whether by representations, oral, written or pictorial derived from the platforms including but not limited to websites/ Application, shall be construed to mean the giving of any warranty of any kind.</li>
                                <li>The Prize(s) under this Contest are neither assignable nor transferable under any circumstance, unless specifically provided hereunder. All the Prizes shall be subject to such other T&C as may be applicable to specific Prize and shall have to be duly complied with by the Winner(s).</li>
                                <li>The Prize(s) to the Winner(s) shall be given subject to compliance with all applicable statutory legislations, processes and formalities in connection with the Prize(s) and on production of all such documents/papers as may be required by Organizer before accepting the delivery of the Prize. Any failure on the part of the Winner(s) to comply with directions issued by Organizer for claim of Prize shall entitle Organizer to forfeit the Prize(s) or roll the Prize over to the next eligible Winner(s), at their sole discretion.</li>
                                <li>Any Participant providing any incorrect information or concealing/withholding any information from Organizer with intent to participate and/or be chosen as the Winner(s) of the Contest will automatically be disqualified from participating in it and being chosen as the Winner(s) of the different categories of Prize. Such act of providing incorrect information or concealing/withholding any information, including without limitation incorrect declaration of information relating to name, age, identity, address, mobile connection of Operator number, domicile etc., by the Participant or dispute with the Platform of Organizer, shall entitle the Organizer to disqualify him/her without any further intimation. Organizer reserves its right to take appropriate legal action against any Participant involved in illegal/unauthorized activity.</li>
                                <li>The Participants shall indemnify and keep indemnified, Organizer and their officers, directors, employees, and affiliates harmless from and against any and all claims, losses, suits, proceedings, action, liabilities, damages, expenses and costs (including attorney’s fees and court costs) which Organizer may incur, pay or become responsible as sponsor/organizer/facilitator as a result of (i) breach or alleged breach of the representations or obligations by the Participants under the T&C hereunder; (ii) any failure by the Participants to comply with applicable law and (iii) any third party claim in respect of misuse of any information of a third party by the Participants. Organizer shall have the right to defend themselves, pursuant to this clause, at the cost of the Participants. Organizer or their respective affiliates shall not be responsible for any direct, indirect, incidental, special, punitive or consequential damages, including loss of profits, incurred by the Winner(s) or any third party, in connection with the Contest. It is expressly provided that transaction shall be between Participant & Organizer only.</li>
                                <li>All incidental costs, taxes or levies related to the Prize(s), if any, shall be exclusively borne by the Winner(s), including but not limited to logistics, TDS, gift tax (if any), Insurance and any other taxes applicable by the Central, State or Municipal government. The Participant(s) who have won the Prize have to make their own arrangements for travel, accommodation to claim the Prize (if applicable); Organizer shall not be responsible for the same or any cost of travel and accommodation incurred by any of them.</li>
                                <li>The Participants hereby irrevocably authorize Organizer and its owners, affiliates, subsidiaries, associates to use the data gathered during and/or after the Contest in respect of the Participants (including but not limited to name and photograph) in any of its communications including marketing promotions and advertisements. By participating in the Contest, Participants confirms to waive the applicability of rules and regulations of the National Do Not Call Registry and agrees to receive updates and promotional messages / SMS / Email / Call for current and future Contests from Organizer.</li>
                                <li>This Contest is subject to force majeure circumstances including without limitation, floods, natural disasters, war, act of terror, political unrests, technical snags, act of God, change of laws or any circumstance beyond the reasonable control of Organizer (“Force Majeure Event”). Organizer shall not be liable for any delay or adverse effect caused to this Contest there under as a result of a Force Majeure Event. Organizer shall intimate the suspension of Contest caused as a result of such Force Majeure Event to the Participants within reasonable time.</li>
                                <li>Organizer reserves all the rights to the Contest any amount/voucher/ as per its sole discretion and to such number of winners as it may deem fit.</li>
                                <li>This Contest is subject to guidelines/ directions issued by any applicable competent authority from time to time.</li>
                                <li>This Contest is designed/sourced by Organizer, are as per their best of efforts. In case there is any discrepancy or dispute regarding the Contest, the decision by Organizer shall be final and neither Organizer nor any third party shall have any liability towards any Participant. No queries/complaints whatsoever in this regard will be entertained.</li>
                                <li>Organizer reserves the right to extend, cancel, discontinue, prematurely withdraw, change, alter or modify this Contest or any part thereof including the eligibility criteria, the T&C and Prize at their sole discretion at any time during its validity as may be required including in view of business exigencies and/or changes by a regulatory authority and/or statutory changes and/or any reasons beyond their control and the same shall be binding on the Participant.</li>
                                <li>Failure by Organizer to enforce any of their rights at any stage does not constitute a waiver of those rights. Further, Organizer may assign any of its rights within the Contest to any party without prior intimation to Participants.</li>
                                <li>Organizer does not make any commitment, express or implied to respond to any feedback, suggestion and/or queries of the Participants.</li>
                                <li>Organizer neither guarantee nor warranty the quality of the goods being included as Prize nor is liable/ responsible for any defect in the goods so obtained/availed, by the Winners under this Contest. Organizer shall also not be liable for any defect in the Prize included in the contest to the Winner. The Winner further understands that the goods provided as Prize will carry manufacturer’s guarantee and in case of any deficiency in the goods, Participant will contact the manufacturer only.</li>
                                <li>The Winners understand and agree that Organizer its owners and affiliates, shall not be liable for any loss or damage whatsoever that may be suffered, or for any personal loss or injury that may be suffered (including loss of life), to a Winner and/or any third party, directly or indirectly, by use or non-use of the Prize.</li>
                                <li>Apart from the entitlement to the Prize, the Winners will at any time have no other rights or claims against Organizer, its owners/organizers/sponsors and affiliates. Notwithstanding anything, in case of any dispute, maximum aggregate liability of Organizer, shall not exceed value of the concerned Prize in case of any dispute in pursuance to the terms and conditions herein.</li>
                                <li>The Winner(s) understand and agree that acceptance of the Prize by them, constitutes grant of permission to and hereby irrevocably authorize the Organizer to click photographs of the Winner and use the Winner’s names, photograph, preferences (likes and dislikes), voice, comments and other personal details for the purpose of this contest including advertising and promotional purposes in any media worldwide, Organizer’s platform or public domain, only for the purposes of advertising and trade without any additional compensation whatsoever to the Winners. The Participant/Winner hereby provides his/her irrevocable consent for sharing/submission of his/her personal information to Organizer, and subsequent use by Organizer of such information for lawful purposes as per its discretion.</li>
                                <li>Post Winner(s) declaration and completion of their announcement and further process as the case may be if Organizer finds that the declared Winner(s) are erroneous then Organizer reserves the right to declare the correct Winner(s) again (as per the T&C) and cancel the Prize of Winner(s) declared earlier and the same decision of Organizer shall not be challenged by any erroneously selected Winners.</li>
                                <li>Organizer shall not be responsible for any claims arising out of technical failures before, during the Contest or after the completion including but not limited to any technical failures in the mobile connectivity, delay in sending or receiving the SMS for participating in the Contest, any action that has been initiated, actioned or completed through his/her mobile phones, failure of servers or any failures arising out of technical snags or resultant inability of the Participants.</li>
                                <li>Post Winner(s) declaration and completion of their announcement and further process as the case may be if Organizer finds that the declared Winner(s) are erroneous then Organizer reserves the right to declare the correct Winner(s) again (as per the T&C) and cancel the Prize of Winner(s) declared earlier and the same decision of Organizer Ecommerce shall not be challenged by any erroneously selected Winners.</li>
                                <li>Organizer shall not be responsible for any claims from any Participant/Winner(s) or any third party arising out of any failure(s) which is beyond the reasonable control of the Organizer. Without limiting the generality of the foregoing, the Organizer shall not be responsible for any claims arising out of technical failures before, during or after the completion of the Contest including but not limited to any technical failures in the mobile/device/computer/laptop connectivity, delay in sending or receiving the SMS for participating in the Contest, any type of delay , any action that has been initiated, actioned or completed through his/her mobile phones/device/computer/laptop, failure of servers or any type of failures arising out of technical snags or resultant inability of the Participant(s). </li>
                                <li>The Participant’s hereby agree and undertake not to hold the Organizer and/or any of their group entities or affiliates, their respective directors, officers, employees, responsible for or liable for, any actions, claims, demands, losses, damages, costs, charges and expenses, either direct or indirect or remote that they may/might have suffered, sustained or incurred, or claim to suffer, sustain or incur, by way of and /or on account of this Contest.</li>
                                <li>Any dispute arising out of this Contest shall first be attempted to be resolved amicably through negotiations. In the event, amicable settlement fails, the dispute shall be referred to the exclusive jurisdiction of the courts at New Delhi courts </li>
                                <li>This Contest and the terms and conditions are subject to Indian laws only .</li>
                            </ul>
                        
                        </article>
                    </div>)
                case 'hindi':
                   return( <div className="loot-tnc">
                        tnc in hindi
                    </div>)
                default:
                    return null;
            }
        })()
    ) 
  }
}

export default TnC;
